services:
  redpanda:
    image: redpandadata/redpanda:v24.3.6
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"

  streams-app:
    build: .
    command: ["run"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      KAFKA_APPLICATION_ID: kafka-streams-demo-real
    depends_on:
      - redpanda
